[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# Ensure environment variables are properly passed to serverless functions
[build.environment]
  NODE_VERSION = "18"

# Global function configuration - simpler approach
[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@solana/*", "@particle-network/*", "@fractalwagmi/*", "@project-serum/*", "@metaplex-*", "solana-*"]

# API endpoints for tracking functions
[[redirects]]
  from = "/api/get-tracking-status"
  to = "/.netlify/functions/get-tracking-status"
  status = 200

[[redirects]]
  from = "/api/register-tracking"
  to = "/.netlify/functions/register-tracking"
  status = 200

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Define the environment variables that are needed but use references to actual values
[template.environment]
  SEVENTEEN_TRACK_API_KEY = "Your 17TRACK API key"

# Redirects
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true
  priority = 100

[[redirects]]
  from = "/service-worker.js"
  to = "/service-worker.js"
  status = 200
  force = true
  priority = 90

[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200
  priority = 80

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
  priority = 50

# Service Worker - ensure correct MIME type and prevent transformations
[[headers]]
  for = "/service-worker.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
    Cache-Control = "no-cache, no-store, must-revalidate"
    X-Content-Type-Options = "nosniff"
    Content-Disposition = "inline"
    Pragma = "no-cache"
    # Prevent Netlify from processing this file
    X-Netlify-Original-Filename = "service-worker.js"

# Manifest file - ensure correct MIME type
[[headers]]
  for = "/manifest.json"
  [headers.values]
    Content-Type = "application/manifest+json; charset=utf-8"
    Cache-Control = "public, max-age=86400"
    X-Content-Type-Options = "nosniff"

# Offline fallback page
[[headers]]
  for = "/offline.html"
  [headers.values]
    Cache-Control = "public, max-age=86400"

# Global security headers and HTML cache control
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' 'unsafe-eval' 'wasm-unsafe-eval'
        https://*.stripe.com https://*.stripe.network https://js.stripe.com 
        https://*.metaplex.com https://*.solana.com
        https://*.phantom.app https://*.backpack.app
        blob:;
      connect-src 'self' 
        https://*.stripe.com https://*.stripe.network https://api.stripe.com https://hooks.stripe.com
        https://*.netlify.app https://*.netlify.com
        https://*.supabase.co https://*.supabase.in wss://*.supabase.co
        https://*.helius-rpc.com https://*.alchemy.com https://*.projectserum.com
        https://rpc.ankr.com https://solana.public-rpc.com https://api.mainnet-beta.solana.com
        https://api.coingecko.com
        https://fonts.googleapis.com https://fonts.gstatic.com
        https://*.metaplex.com https://cdn.metaplex.com https://arweave.net https://*.arweave.net
        https://*.genesysgo.net https://*.solana.com
        https://*.helius.xyz https://*.helius.dev
        https://*.magiceden.io https://*.magiceden.dev
        https://*.tensor.trade
        https://*.phantom.app https://*.backpack.app
        https://*.jupiter.ag https://*.jup.ag
        https://store.fun https://*.store.fun
        wss://*.solana.com ws://*.solana.com
        blob:
        data:;
      frame-src 'self' 
        https://*.stripe.com https://*.stripe.network https://js.stripe.com https://hooks.stripe.com 
        https://*.solana.com https://*.phantom.app https://*.backpack.app;
      img-src 'self' data: blob: 
        https://*.stripe.com https://*.netlify.app https://*.netlify.com 
        https://*.supabase.co https://*.arweave.net https://arweave.net 
        https://*.nftstorage.link https://*.ipfs.io https://*.ipfs.dweb.link
        https://*.metaplex.com https://cdn.metaplex.com
        https://*.cloudfront.net https://*.amazonaws.com
        https://*.magiceden.io https://*.magiceden.dev
        https://*.tensor.trade;
      style-src 'self' 'unsafe-inline' https://*.stripe.com https://fonts.googleapis.com;
      font-src 'self' https://fonts.gstatic.com data:;
      worker-src 'self' blob: 'wasm-unsafe-eval';
      child-src 'self' blob:;
      object-src 'none';
      base-uri 'self';
      form-action 'self';
      manifest-src 'self';
      media-src 'self' blob: data:;
      upgrade-insecure-requests;
    """
    # Short cache for HTML files
    Cache-Control = "public, max-age=0, must-revalidate"

# Images with improved caching strategy
[[headers]]
  for = "/*.{jpg,jpeg,png,gif,webp,svg,avif}"
  [headers.values]
    Cache-Control = "public, max-age=86400, stale-while-revalidate=604800"
    X-Cache-Type = "IMAGES"
    X-Cache-Strategy = "dynamic"

# Static assets with hash (immutable) - most specific first
[[headers]]
  for = "/assets/*-*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    X-Cache-Type = "STATIC"
    X-Cache-Strategy = "immutable"

# Regular static assets - more general pattern
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=86400, stale-while-revalidate=604800"
    X-Cache-Type = "ASSETS"
    X-Cache-Strategy = "dynamic"

# JavaScript modules - ensure correct MIME type
[[headers]]
  for = "/assets/*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
    Cache-Control = "public, max-age=31536000, immutable"
    X-Cache-Type = "JS_MODULE"
    X-Cache-Strategy = "immutable"

# API responses - short cache with revalidation
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Cache-Control = "public, max-age=60, stale-while-revalidate=300"
    X-Cache-Strategy = "dynamic"

# Supabase storage assets - with CORS headers
[[headers]]
  for = "/storage/*"
  [headers.values]
    Cache-Control = "public, max-age=2592000, stale-while-revalidate=31536000"
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, HEAD, OPTIONS"
    Access-Control-Allow-Headers = "Accept, Authorization, Cache-Control, Content-Type, Keep-Alive, Origin, X-Client-Info"
    Access-Control-Expose-Headers = "Content-Length, Content-Range"
    Access-Control-Max-Age = "86400"
    Timing-Allow-Origin = "*"
    X-Cache-Type = "IMAGES"
    X-Cache-Strategy = "dynamic"

# Additional headers for Supabase render endpoint
[[headers]]
  for = "/.netlify/functions/supabase-proxy/*"
  [headers.values]
    Cache-Control = "public, max-age=2592000, stale-while-revalidate=31536000"
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, HEAD, OPTIONS"
    Access-Control-Allow-Headers = "Accept, Authorization, Cache-Control, Content-Type, Keep-Alive, Origin, X-Client-Info"
    Access-Control-Expose-Headers = "Content-Length, Content-Range"
    Access-Control-Max-Age = "86400"
    Timing-Allow-Origin = "*"
    X-Cache-Type = "IMAGES"
    X-Cache-Strategy = "dynamic"

# Add specific proxy for Supabase image render endpoints
[[redirects]]
  from = "/image-proxy/*"
  to = "https://:splat"
  status = 200
  force = true
  headers = {Cache-Control = "public, max-age=2592000, stale-while-revalidate=31536000"}

# NFT Metadata
[[headers]]
  for = "/api/nft/*"
  [headers.values]
    Cache-Control = "public, max-age=3600, stale-while-revalidate=7200"
    X-Cache-Type = "NFT_METADATA"

[[headers]]
  for = "/api/metadata/*"
  [headers.values]
    Cache-Control = "public, max-age=3600, stale-while-revalidate=7200"
    X-Cache-Type = "NFT_METADATA"

# Product Data
[[headers]]
  for = "/api/products/*"
  [headers.values]
    Cache-Control = "public, max-age=300, stale-while-revalidate=600"
    X-Cache-Type = "PRODUCT_DATA"

[[headers]]
  for = "/api/categories/*"
  [headers.values]
    Cache-Control = "public, max-age=300, stale-while-revalidate=600"
    X-Cache-Type = "PRODUCT_DATA"

# Dynamic Data
[[headers]]
  for = "/api/pricing/*"
  [headers.values]
    Cache-Control = "public, max-age=30, stale-while-revalidate=60"
    X-Cache-Type = "DYNAMIC_DATA"

[[headers]]
  for = "/api/stock/*"
  [headers.values]
    Cache-Control = "public, max-age=30, stale-while-revalidate=60"
    X-Cache-Type = "DYNAMIC_DATA"

# No Cache for Critical Operations
[[headers]]
  for = "/api/blockchain/*"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate"
    Pragma = "no-cache"

[[headers]]
  for = "/api/checkout/*"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate"
    Pragma = "no-cache"

[[headers]]
  for = "/api/payment/*"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate"
    Pragma = "no-cache"

[[headers]]
  for = "/api/auth/*"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate"
    Pragma = "no-cache"

[[headers]]
  for = "/api/orders/*"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate"
    Pragma = "no-cache"

# Version endpoint
[[headers]]
  for = "/api/version"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate"
    Pragma = "no-cache" 