[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22"

# Asset handling
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    # Short cache for HTML files
    Cache-Control = "public, max-age=0, must-revalidate"

# Medium cache for unhashed assets (more general pattern first)
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"

# Long cache for hashed assets (more specific pattern last)
[[headers]]
  for = "/assets/*-*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# API responses - short cache with revalidation
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Cache-Control = "public, max-age=60, stale-while-revalidate=300"

# Supabase storage assets - longer cache
[[headers]]
  for = "/storage/*"
  [headers.values]
    Cache-Control = "public, max-age=86400, stale-while-revalidate=604800"

# Handle client-side routing
[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true 